-- AlterTable
ALTER TABLE `audit_log` MODIFY `action` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'ACCESS_DENIED', 'USER_CREATED', 'USER_PROFILE_UPDATED', 'CR_CREATED', 'CR_SUBMITTED', 'CR_REVIEWED', 'CR_APPROVED', 'CR_ASSIGNEES_CHANGED', 'CR_APPLIED', 'CR_ROLLED_BACK', 'TARGET_DB_CREATED', 'TARGET_DB_UPDATED', 'TARGET_DB_DELETED', 'SQL_POLICY_UPDATED', 'APPROVAL_POLICY_UPDATED', 'APPLY_WINDOW_UPDATED', 'FREEZE_UPDATED') NOT NULL,
    MODIFY `targetType` ENUM('CHANGE_REQUEST', 'USER', 'TARGET_DATABASE', 'EXECUTION', 'AUTH', 'SQL_REVIEW_POLICY', 'APPROVAL_POLICY', 'APPLY_SCHEDULE') NOT NULL;

-- CreateTable
CREATE TABLE `apply_window` (
    `id` VARCHAR(191) NOT NULL,
    `env` ENUM('DEV', 'STAGING', 'PROD') NOT NULL,
    `dayOfWeek` INTEGER NOT NULL,
    `startMinute` INTEGER NOT NULL,
    `endMinute` INTEGER NOT NULL,

    INDEX `apply_window_env_idx`(`env`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `freeze_period` (
    `id` VARCHAR(191) NOT NULL,
    `env` ENUM('DEV', 'STAGING', 'PROD') NOT NULL,
    `startsAt` DATETIME(3) NOT NULL,
    `endsAt` DATETIME(3) NOT NULL,
    `reason` VARCHAR(191) NOT NULL,
    `createdById` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `freeze_period_env_idx`(`env`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `freeze_period` ADD CONSTRAINT `freeze_period_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
